### ISSUE TITLE
Dubious PR

### ISSUE THREAD

**Issue by antonreshetov** [c0d3G33k/massCode-Code-execution#1]
Wow, so fast to spread the word for dubious PR, instead of solving the problem. Praise.

**Comment by c0d3G33k** [comment]
I understand your pain, my friend! you keep closing bug issues without any information. Good luck!

**Comment by antonreshetov** [comment]
And you too, make the world a better place!
And most importantly, ask people to contact you by email instead of immediately describing Issue

**Comment by antonreshetov** [comment]
Wow you delete the comment! ))

**Comment by c0d3G33k** [comment]
Yes, this is what I prefer for reporting security bugs! and I haven't deleted any of your comment!
